language: python
python: 2.7
env:
- TOX_ENV=py27
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
- pip install nose numpy scipy tox
script:
- tox -e $TOX_ENV
notifications:
  slack:
    secure: WhXthdzThHNvuAu3UTM71umvUxK1PzvXHto8xrYzTqwpjUsFXZ+uaEBi/FZikThov04un11eC5ct5XtdESrw8Nh0nCTonVXTIqMsWCaNrj3mZHK7kXPKlfrIoVlpy/s3cAAZ739P0GcRnXDfCJr4dXF7js5uczMU4dhW0ZaDAlY=
